# Generated by Django 6.0.4 on 2026-05-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="book title")),
                (
                    "author",
                    models.CharField(max_length=100, verbose_name="author name"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="book price"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="book description"),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="book stock"),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="books", to="categories.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "book",
                "verbose_name_plural": "books",
                "ordering": ["title"],
            },
        ),
    ]
